### ISSUE TITLE
Unfixable problems about meRanGs align

### ISSUE THREAD

**Issue by Kaixin-Huang** [icbi-lab/meRanTK#1]
Dear Prof. Dietmar Rieder,

I downloaded the latest version of meRanTK(1,3,0) and installed with "the easy way". While running meRanGs align on the server of our lab (CentOS 8), I kept encountering this ERROR: “Can't locate object method "new" via package "GD::Graph::lines" at script/meRanGh.pl line 4807.

However, I already installed GD and GDGraph. To make sure of this, I wrote a simple perl scrip called test.pl (use GD::Graph::lines), and run perl test.pl, there is no warning and errors. In the directory of perl , I could find GD/Graph/lines.pm, and GD/GD.pm, etc.

I've been stuck on this for quit a few days, I've tried to re-install perl and GD and other required modules for m bias plot. But none of these get work.

I would be really appreciated if meRanTK developer team members could provide some other methods to solve this. Thanks for your effort on this great toolkit.

Best Regards

**Comment by riederd** [comment]
Hi, thanks for your interest in meRanTK and for reporting this issue. We will have a look into it and try to reproduce the problem.
Meanwhile you could try to use the provided conda env to run the tools

``

**Comment by riederd** [comment]
Hi, thanks for your interest in meRanTK and for reporting this issue. We will have a look into it and see if we can reproduce the problem. Meanwhile you could try to run the tools with the provided conda env.

```
conda env create --name merantk –file=merantk.yml
mv extutil extutil_back
conda activate merantk

```

**Comment by Kaixin-Huang** [comment]
Sadly another error occurred:
`# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/huangkx/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1114, in __call__
        return func(*args, **kwargs)
      File "/home/huangkx/miniconda3/lib/python3.9/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/huangkx/miniconda3/lib/python3.9/site-packages/conda_env/cli/main_create.py", line 90, in execute
        spec = specs.detect(name=name, filename=get_filename(args.file), directory=os.getcwd())
      File "/home/huangkx/miniconda3/lib/python3.9/site-packages/conda_env/specs/__init__.py", line 47, in detect
        if spec.can_handle():
      File "/home/huangkx/miniconda3/lib/python3.9/site-packages/conda_env/specs/binstar.py", line 39, in can_handle
        result = self._can_handle()
      File "/home/huangkx/miniconda3/lib/python3.9/site-packages/conda_env/specs/binstar.py", line 54, in _can_handle
        return self.package is not None and self.valid_package()
      File "/home/huangkx/miniconda3/lib/python3.9/site-packages/conda_env/specs/binstar.py", line 118, in package
        self._package = self.binstar.package(self.username, self.packagename)
      File "/home/huangkx/miniconda3/lib/python3.9/site-packages/binstar_client/__init__.py", line 298, in package
        self._check_response(res)
      File "/home/huangkx/miniconda3/lib/python3.9/site-packages/binstar_client/__init__.py", line 226, in _check_response
        raise ErrCls(msg, res.status_code)
    binstar_client.errors.ServerError: ('The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.', 500)

`$ /home/huangkx/miniconda3/bin/conda-env create --name merantk –file=./merantk.yml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/huangkx/miniconda3/bin/conda
               CONDA_HOME=/home/huangkx/miniconda3
             CONDA_PREFIX=/home/huangkx/miniconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/home/huangkx/miniconda3/bin/python
               CONDA_ROOT=/home/huangkx/miniconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                     PATH=/home/huangkx/miniconda3/bin:/home/huangkx/miniconda3/bin:/home/huangk
                          x/miniconda3/condabin:/home/huangkx/miniconda3/bin:/usr/local/bin:/usr
                          /bin:/usr/local/sbin:/usr/sbin:/home/huangkx/bin:/home/huangkx/bioinfo
                          /app/gdc:/home/huangkx/bioinfo/app/salmon/salmon-latest_linux_x86_64/b
                          in:/home/huangkx/bioinfo/app/java11/jdk-11.0.1/bin:/home/huangkx/bioin
                          fo/app/genephredtogtf:/home/huangkx/bioinfo/app/blast+/ncbi-blast-2.12
                          .0+/bin:/home/huangkx/bioinfo/app/homer/bin:/home/huangkx/bioinfo/app/
                          bedGraphToBigWig:/home/huangkx/bioinfo/app/ucsc_liftover:/home/huangkx
                          /bioinfo/app/node/bin:/home/huangkx/bioinfo/app/nuohe/linuxnd:/home/hu
                          angkx/bioinfo/app/salmon/salmon-1.8.0_linux_x86_64/bin:/home/huangkx/b
                          ioinfo/app/fastp
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /home/huangkx/miniconda3
            shell level : 1
       user config file : /home/huangkx/.condarc
 populated config files : /home/huangkx/.condarc
          conda version : 4.13.0
    conda-build version : not installed
         python version : 3.9.1.final.0
       virtual packages : __linux=4.18.0=0
                          __glibc=2.28=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/huangkx/miniconda3  (writable)
      conda av data dir : /home/huangkx/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/noarch
          package cache : /home/huangkx/miniconda3/pkgs
                          /home/huangkx/.conda/pkgs
       envs directories : /home/huangkx/miniconda3/envs
                          /home/huangkx/.conda/envs
               platform : linux-64
             user-agent : conda/4.13.0 requests/2.27.1 CPython/3.9.1 Linux/4.18.0-240.22.1.el8_3.x86_64 centos/8.3.2011 glibc/2.28
                UID:GID : 1003:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.`

**Comment by Kaixin-Huang** [comment]
> 

I successfully created the conda env using : conda env create -f merantk.yml -n merantk ;

To make sure, if I want to run meRanTK through this env I need to:

conda activate merantk

Then run：
/my_path/meRanGs align ......

Am I right?

I will reply immediately if I don't encounter errors about GD graph.

Thank you!

**Comment by riederd** [comment]
The error looks like a remote conda server error to me, it says:

`"Either the server is overloaded or there is an error in the application"`

I don't think this is related to meRanTK, you may just retry and if it is not working check your conda installation.
I just tried on our side and it worked fine.

To be sure, that you have the correct conda channels added please run the following before creating the env:

```
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge

conda env create -name merantk -f merantk.yml
```

**Comment by riederd** [comment]
> I successfully created the conda env using : conda env create -f merantk.yml -n merantk ;

Good

> To make sure, if I want to run meRanTK through this env I need to:
> 
> conda activate merantk
> 
> Then run： /my_path/meRanGs align ......

You need to copy src perl script to the meRanTK dir:

`cp <path to>/meRanTK-1.3.0/src/*.pl <path to>/meRanTK-1.3.0/`

and then run the perl script from there:

`<path to>/meRanTK-1.3.0/meRanGs.pl align`
 
> I will reply immediately if I don't encounter errors about GD graph.

Yeah thanks

**Comment by Kaixin-Huang** [comment]
The M-bias plot has been successfully generated. I think this problem could be solved by installing meRanTK using yml and running perl scripts in ./scr.

Thank you so much for your timely and detailed reply!
